---
title: "Homework 3"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(caret)
library(glmnet)
library(pls)
library(splines)
library(mgcv)
library(pdp)
library(earth)
library(doParallel)
library(ISLR)

knitr::opts_chunk$set(
  fig.height = 6,
  fig.width = 8,
  message = F,
  echo = T,
  warning = F,
  cache = T
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
  digits = 3
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


# 1

## 1
```{r}
data("Weekly")

Weekly = Weekly %>% 
  janitor::clean_names() %>% 
  select(-today)

skimr::skim_without_charts(Weekly)

caret::featurePlot(model.matrix(direction~.,Weekly %>% select(-year)),Weekly$direction,"pairs")

Weekly_Tr = Weekly %>% 
  filter(year <=2008)

Weekly_Ts = Weekly %>% 
  filter(year > 2008)
```

```{r echo=FALSE}
X_tr = model.matrix(direction~.,Weekly_Tr %>% select(-year))[,-1]
X_ts = model.matrix(direction~.,Weekly_Ts %>% select(-year))[,-1]
Y_tr = Weekly_Tr$direction
Y_ts = Weekly_Ts$direction

TRC = trainControl(
  "repeatedcv",
  number = 5,
  repeats = 5,
  summaryFunction = twoClassSummary,
  classProbs = TRUE
)

```



## 2

```{r logistic}
Weekly_logistic =
  train(
    X_tr,
    Y_tr,
    method = "glm",
    family = "binomial",
    trControl = TRC,
    metric = "ROC",
    preProcess = c("center", "scale")
  )
```
```{r}
logistic_prediction = 
  predict(Weekly_logistic,newdata = X_ts, type = "raw")

confusionMatrix(logistic_prediction,Y_ts)
```

## 3

```{r}
Weekly_logistic2 = 
  train(model.matrix(direction~lag1+lag2,Weekly_Tr)[,-1],
        Y_tr,
        method = "glm",
        metric = "ROC",
        trControl = TRC,
        preProcess = c("center","scale"))
```

```{r roc}
logistic_roc = pROC::roc(Y_ts,predict(Weekly_logistic2,newdata = X_ts,type = "prob")[,2])
```

## 4

### LDA
```{r}
Weekly_lda = 
  train(model.matrix(direction~lag1+lag2,Weekly_Tr)[,-1],
        Y_tr,
        method = "lda",
        metric = "ROC",
        trControl = TRC,
        preProcess = c("center","scale"))
```

```{r ldaroc}
lda_roc = pROC::roc(Y_ts,predict(Weekly_lda,newdata = X_ts,type = "prob")[,2])
```

### QDA
```{r}
Weekly_qda = 
  train(model.matrix(direction~lag1+lag2,Weekly_Tr)[,-1],
        Y_tr,
        method = "qda",
        metric = "ROC",
        trControl = TRC,
        preProcess = c("center","scale"))
```

```{r qdaroc}
qda_roc = pROC::roc(Y_ts,predict(Weekly_qda,newdata = X_ts,type = "prob")[,2])

auc = c()

ROC = list(logistic_roc,lda_roc,qda_roc)

for (i in 1:3){
  auc = append(auc,ROC[[i]]$auc[1])
  plot(ROC[[i]],col = i, add = T * (i>1), legacy.axes = T * (i==1))
}

model_name = 
  c("logistic","LDA","QDA")

legend("bottomright",
       legend = paste0(model_name,"~",round(auc,3)),col=1:3,lwd=2)
```