---
title: "Homework 2"
author: "Jeffrey LIANG"
date: "2/20/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(caret)
library(glmnet)
library(pls)
library(splines)
library(mgcv)
library(pdp)
library(earth)
library(doParallel)

knitr::opts_chunk$set(
  fig.height = 6,
  fig.width = 8,
  message = F,
  echo = T,
  warning = F,
  cache = T
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
  digits = 3
)


scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```

```{r}
set.seed(123123)
```

# Q1

```{r echo = F}
clg_data =
  read_csv("College.csv") %>% 
  janitor::clean_names() %>% 
  mutate(
    college = as.factor(college)
  )

skimr::skim_without_charts(clg_data)
```

Missing data is the respone, omitting the data instead of treating with data preprocessing.

```{r data_preprocess}
clg_data = clg_data %>% drop_na()

train_index = createDataPartition(clg_data$outstate, p = 0.8, list = F)

clg_train = clg_data[train_index,]

clg_test = clg_data[-train_index,]

Y_train = clg_train$outstate

X_train = model.matrix(outstate ~., data = clg_train)[,-1]

Y_ts = clg_test$outstate

X_ts = model.matrix(outstate ~., data = clg_test)[,-1]

ctrl = trainControl(method = "repeatedcv",number = 5, repeats = 5)

clg_data %>% 
  select(-college,-outstate) %>% 
  featurePlot(.,clg_data$outstate,plot = "scatter",row = 4)
```



# Q2

```{r smooth_spline}
clg_ss_cv = smooth.spline(clg_train$terminal, Y_train, cv = T)

clg_ss =
  tibble(
    x = list(clg_train$terminal),
    y = list(Y_train),
    x_t = list(clg_test$terminal),
    y_t = list(Y_ts),
    df = list(seq(2, 20, length = 5)%/%1)
  ) %>%
  unnest(df) %>%
  mutate(model = pmap(list(x, y, df),
                      function(x, y, df, ...)
                        smooth.spline(
                          x = x, y = y, df = df
                        ))) %>%
  rbind(list(
    x = list(clg_train$terminal),
    y = list(Y_train),
    x_t = list(clg_test$terminal),
    y_t = list(Y_ts),
    df = clg_ss_cv$df,
    model = list(clg_ss_cv)
  )) %>%
  mutate(
    prediction = map2(.x = x_t,
                      .y = model,
                      ~predict(object = .y,x = .x,se=F)$y),
    df = as.factor(df)
  ) %>%
  select(df, y_t, prediction, x_t) %>%
  unnest(c(prediction, y_t,x_t))

clg_ss %>%
  group_by(df) %>%
  summarise(mse =
              mean((y_t - prediction) ^ 2)) %>% 
  knitr::kable(caption = "Smooth spline performance with different degree of freedom",digits = 3)

ggplot(clg_ss) +
  geom_point(aes(x = x_t, y = y_t)) +
  geom_line(aes(x = x_t, y = prediction, color= df)) +
  facet_wrap(df ~ ., nrow = 2) +
  labs(title = "Smooth Spline")
```



The model obtained from CV method has the degree of freedom of `r clg_ss_cv$df` and lambda `r clg_ss_cv$lambda` has the lowest MSE in the model candidates.



# Q3
```{r gam, cache=T}
cl = makePSOCKcluster(5)# if windows, set to 1

registerDoParallel(cl)

clg_gam =
  train(
    x = X_train,
    y = Y_train,
    method = "gam",
    tuneGrid = expand.grid(select = c(T, F),
                           method  = c("GCV.cp", "REML")),
    metric = "RMSE",
    trControl = ctrl
  )

stopCluster(cl)

clg_gam$bestTune

summary(clg_gam$finalModel)

par(mfrow = c(2,4))

plot(clg_gam$finalModel)

par(mfrow=c(1,2))
for (i in 1:8){
  predictor = clg_gam$finalModel$terms %>% attr("term.labels") %>% .[(2*i-1):(2*i)]
  vis.gam(clg_gam$finalModel,predictor)
}
```

Using caret tuning, the best tuning methods is `select = F` and `method = "REML"`

# Q4

```{r mars,cache=T}
cl = makePSOCKcluster(5) #if windows, set to 1
registerDoParallel(cl)
clg_mars =
  train(
    x = X_train,
    y = Y_train,
    method = "earth",
    tuneGrid = expand.grid(degree = 1:3,
                           nprune = exp(
                             seq(1, log(100), length = 10)
                           )%/%1),
    metric = "RMSE",
    trControl = ctrl
  )
stopCluster(cl)

clg_mars$finalModel$coefficients %>% 
  knitr::kable(caption = "Hints")

ggplot(clg_mars)

clg_mars$bestTune

summary(clg_mars$finalModel)

p1 = pdp::partial(clg_mars, pred.var = c("grad_rate", "f_undergrad")) %>%
  plotPartial(
    levelplot = FALSE,
    zlab = "yhat",
    drape = TRUE,
    screen = list(z = 20, x = -60)
  )

p2 = pdp::partial(clg_mars, pred.var = c("apps", "enroll")) %>%
  plotPartial(
    levelplot = FALSE,
    zlab = "yhat",
    drape = TRUE,
    screen = list(z = 20, x = -60)
  )

grid.arrange(p1,p2,nrow = 2)
```

```{r resample}
rmp = caret::resamples(list(gam = clg_gam,
                            mars = clg_mars))

summary(rmp)


```


