---
title: "Homework_1"
author: "Jeffrey LIANG"
date: "2/4/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(caret)
library(pls)

knitr::opts_chunk$set(
  fig.height = 6,
  fig.width = 8,
  message = F,
  echo = T,
  warning = F,
  cache = T
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis",
  digits = 3
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```


```{r}
set.seed(123123)
sl_tr =
  read_csv(here::here("solubility_train.csv")) %>% 
  janitor::clean_names()

sl_ts =
  read_csv(here::here("solubility_test.csv")) %>% 
  janitor::clean_names()

x_ts = model.matrix(solubility ~ ., sl_ts)[, -1]

y_ts = sl_ts$solubility
```


# Q1
```{r lm}
sl_lm =
  train(solubility~.,
        data = sl_tr,
        method = "lm",
        trControl = 
          trainControl(
            method = "repeatedcv",
            number = 10,
            repeats = 5
          ))


RMSE(predict(sl_lm,newdata = sl_ts),sl_ts$solubility)
```
# Q2
```{r ridge}
sl_ridge =
  train(
    solubility ~ .,
    data = sl_tr,
    method = "glmnet",
    tuneGrid =
      expand.grid(alpha = 0,
           lambda = exp(seq(from = -1,to =-3, length = 1000))),
    trControl =
      trainControl(method = "repeatedcv",
                   number = 10,
                   repeats = 5),
    preProcess = c("center","scale")
  )

plot(sl_ridge, xTrans = log)

sl_ridge$bestTune

RMSE(predict(sl_ridge,s="lambda.min",newx = sl_ts),sl_ts$solubility)
```


# Q3
```{r}
sl_lasso =
  train(
    solubility~.,
    data = sl_tr,
    method = "glmnet",
    tuneGrid = 
      expand.grid(alpha = 1,
             lambda = exp(seq(-6,to=1,length = 1000))),
    trControl = 
      trainControl(
        method = "repeatedcv",
        number = 10,
        repeats = 5
      ),
    preProcess = 
      c("center","scale")
  )

plot(sl_lasso,xTrans = log)

sl_lasso$bestTune

plotmo::plot_glmnet(
  sl_lasso$finalModel
)

sum(coef(sl_lasso$finalModel, s = sl_lasso$bestTune$lambda)!=0)

RMSE(predict(sl_lasso,s="lambda.min",newx = sl_ts),sl_ts$solubility)
```


# Q4
```{r pcr}
sl_pcr =
  train(
    solubility~.,
    data = sl_tr,
    method = "pcr",
    tuneGrid = 
      expand.grid(ncomp = seq(1,ncol(sl_tr))),
    preProcess = c("center","scale"),
    trControl =
      trainControl(
        method = "repeatedcv",
        number = 10,
        repeats = 5
      )
  )

sl_pcr$bestTune

validationplot(sl_pcr$finalModel,val.type = "MSEP")

RMSE(predict(sl_pcr,x_ts),y_ts)

mean((predict(sl_pcr,x_ts)-y_ts)^2)
```


```{r}
resam = 
  resamples(list(
    lm = sl_lm,
    ridge = sl_ridge,
    lasso = sl_lasso,
    pcr = sl_pcr
  ))

summary(resam)

bwplot(resam, metric = "RMSE")
```

By the resampling result, we can see that Lasso method has the best/lowest mean RMSE and MAE, as well as the highest $R^2$. Lasso will be chosen to use out of the four for its predictivity and goodness of fit.
